{% set name = "mosaic-clustering" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mosaic-clustering-{{ version }}.tar.gz
  sha256: 6454f2d68201731a7a4a66ee9fc0daf876dbf88ab977903b877ed364d145ccfa

build:
  noarch: python
  entry_points:
    - mosaic = mosaic.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - beartype >=0.10.4
    - click >=7.0.0
    - leidenalg >=0.8.0
    - numpy >=1.21.0
    - pandas
    - prettypyplot
    - python >=3.8
    - python-igraph
    - scikit-learn
    - scikit-learn-extra
    - scipy
    - typing-extensions >=3.9.0

test:
  imports:
    - mosaic
  commands:
    - pip check
    - mosaic --help
  requires:
    - pip

about:
  home: https://github.com/moldyn/MoSAIC
  summary: Correlation based feature selection for molecular dynamics data
  license: MIT
  license_file: LICENSE
  description: |
    MoSAIC is an unsupervised method for correlation analysis which
    automatically detects the collective motion in MD simulation data, while
    simultaneously identifying uncorrelated coordinates as noise. Hence, it can
    be used as a feature selection scheme for Markov state modeling or simply
    to obtain a detailed picture of the key coordinates driving a biomolecular
    process. It is based on the Leiden community detection algorithm which is
    used to bring a correlation matrix in a block-diagonal form.
  doc_url: https://moldyn.github.io/MoSAIC/

extra:
  recipe-maintainers:
    - braniii
